apiVersion: apps/v1
kind: deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-deployment
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      container:
        - name ngnix
          image: nginx:latest
          ports:
            - containerPort: 80